sclorg/helm-charts

charts/redhat/postgresql-persistent/OWNERS
charts/redhat/varnish-imagestreams/OWNERS
charts/redhat/varnish-imagestreams/src/Chart.yaml
charts/redhat/varnish-imagestreams/src/templates/imagestreams.yaml
tests/test_varnish_imagestreams.py

This pull request adds Varnish Helm chart imagestreams.

Add Varnish Helm Chart for imagestreams

---

.github/workflows/openshift-tests.yaml
Makefile

Split tests to more

---

charts/redhat/httpd-imagestreams/OWNERS
charts/redhat/httpd-template/OWNERS

Add OWNERS file and fix imagestream OWNERS

---

Makefile

Add test-all target

---

.github/workflows/openshift-tests.yaml

Add support for testing php and perl imagestreams and templates

---

.github/workflows/openshift-tests.yaml
Makefile

Add support for testing NodeJS Python and Ruby imagestreams

---

Makefile

Fix calling test-perl

---

Makefile
charts/redhat/httpd-template/src/Chart.yaml
charts/redhat/httpd-template/src/templates/tests/test-httpd-connection.yaml
charts/redhat/nginx-imagestreams/src/Chart.yaml
charts/redhat/nginx-imagestreams/src/templates/imagestreams.yaml
charts/redhat/nginx-template/OWNERS
charts/redhat/nginx-template/src/Chart.yaml
charts/redhat/nginx-template/src/README.md
charts/redhat/nginx-template/src/templates/buildconfig.yaml
charts/redhat/nginx-template/src/templates/deployment.yaml
charts/redhat/nginx-template/src/templates/imagestream.yaml
charts/redhat/nginx-template/src/templates/route.yaml
charts/redhat/nginx-template/src/templates/service.yaml
charts/redhat/nginx-template/src/templates/tests/test-nginx-connection.yaml
charts/redhat/nginx-template/src/values.schema.json
charts/redhat/nginx-template/src/values.yaml
tests/test_httpd_template.py
tests/test_nginx_imagestreams.py
tests/test_nginx_template.py

Add new Nginx version to imagestreams
Add nginx-template with Deployment

Nginx template

---

charts/redhat/perl-imagestreams/src/templates/perl-imagestreams.yaml
tests/test_perl_dancer_app.py
tests/test_perl_dancer_mysql_template.py
tests/test_perl_imagestreams.py

EOL perl imagestreams

---

charts/redhat/nginx-template/src/Chart.yaml
charts/redhat/php-cakephp-application/OWNERS
charts/redhat/php-cakephp-application/src/Chart.yaml
charts/redhat/php-cakephp-application/src/templates/buildconfig.yaml
charts/redhat/php-cakephp-application/src/templates/deployment.yaml
charts/redhat/php-cakephp-application/src/templates/imagestream.yaml
charts/redhat/php-cakephp-application/src/templates/route.yaml
charts/redhat/php-cakephp-application/src/templates/secret.yaml
charts/redhat/php-cakephp-application/src/templates/service.yaml
charts/redhat/php-cakephp-application/src/templates/tests/test-php-cakephp-connection.yaml
charts/redhat/php-cakephp-application/src/values.schema.json
charts/redhat/php-cakephp-application/src/values.yaml
tests/test_php_cakephp_application.py

This pull request adds support for the CakePHP application.

Add support for PHP CakePHP application helm chart

---

index.yaml

Index update

---

charts/redhat/nodejs-imagestreams/src/Chart.yaml
charts/redhat/nodejs-imagestreams/src/templates/nodejs-imagestream.yaml
tests/test_nodejs_imagestreams.py

NodeJS 16 reached EOL. Deprecate it

---

.github/workflows/openshift-tests.yaml

Fix_halm_chart_name

---

charts/centos/httpd-imagestreams/src/Chart.yaml
charts/centos/httpd-imagestreams/src/templates/imagestreams.yaml
charts/centos/mariadb-imagestreams/src/Chart.yaml
charts/centos/mariadb-imagestreams/src/templates/imagestreams.yaml
charts/centos/mysql-imagestreams/src/Chart.yaml
charts/centos/mysql-imagestreams/src/templates/imagestreams.yaml
charts/centos/postgresql-imagestreams/src/Chart.yaml
charts/centos/postgresql-imagestreams/src/templates/imagestreams.yaml
charts/centos/redis-imagestreams/src/Chart.yaml
charts/centos/redis-imagestreams/src/templates/imagestreams.yaml
tests/test_httpd_imagestreams.py
tests/test_mariadb_imagestreams.py
tests/test_mysql_imagestreams.py
tests/test_postgresql_imagestreams.py
tests/test_redis_imagestreams.py

Remove C8S imagestreams and check that they are not present

---

Makefile
charts/centos/valkey-imagestreams/OWNERS
charts/centos/valkey-imagestreams/src/Chart.yaml
charts/centos/valkey-imagestreams/src/templates/imagestreams.yaml
tests/test_valkey_imagestreams.py

Add support for CentOS Stream 10 valkey imagestreams

---

charts/redhat/php-cakephp-application/src/Chart.yaml
charts/redhat/php-cakephp-application/src/templates/deployment.yaml
charts/redhat/php-cakephp-application/src/values.schema.json
charts/redhat/php-cakephp-application/src/values.yaml

Fix php application and add 8.2 imagestreams

---

charts/redhat/ruby-rails-application/src/values.schema.json

Update rails with up2date imagestreams

---

charts/redhat/ruby-rails-application/src/templates/buildconfig.yaml
tests/test_ruby_rails_application.py

Test all ruby supported version

---

charts/redhat/nodejs-application/src/templates/buildconfig.yaml

Fix to git.ref and git.uri. It should be strings

---

charts/redhat/ruby-rails-application/src/templates/deployment.yaml
tests/test_ruby_rails_application.py

This pull request fixes deployment and test suite for ruby application

Fix ruby helm chart

---

charts/redhat/php-cakephp-application/src/templates/buildconfig.yaml
charts/redhat/php-cakephp-application/src/templates/deployment.yaml
charts/redhat/php-cakephp-application/src/templates/tests/test-php-cakephp-connection.yaml
charts/redhat/php-cakephp-application/src/values.schema.json
charts/redhat/php-cakephp-application/src/values.yaml
tests/test_nginx_imagestreams.py
tests/test_php_cakephp_application.py

To values.yaml file were added registry options
values.json file was updated accordingly

Allows to check PHP HelmCharts in Shared Cluster.

---

charts/redhat/httpd-template/src/templates/buildconfig.yaml
charts/redhat/httpd-template/src/templates/deployment.yaml
charts/redhat/httpd-template/src/values.schema.json
charts/redhat/httpd-template/src/values.yaml
charts/redhat/mariadb-persistent/src/templates/persistentvolumeclaim.yaml
charts/redhat/mariadb-persistent/src/values.schema.json
charts/redhat/mariadb-persistent/src/values.yaml
charts/redhat/mysql-persistent/src/templates/persistentvolumeclaim.yaml
charts/redhat/mysql-persistent/src/values.schema.json
charts/redhat/mysql-persistent/src/values.yaml
charts/redhat/redis-persistent/src/templates/persistentvolumeclaim.yaml
charts/redhat/redis-persistent/src/values.schema.json
charts/redhat/redis-persistent/src/values.yaml
tests/test_httpd_imagestreams.py
tests/test_httpd_template.py
tests/test_mariadb_imagestreams.py
tests/test_mariadb_template.py
tests/test_mysql_imagestreams.py
tests/test_mysql_template.py
tests/test_redis_imagestreams.py
tests/test_redis_template.py

This pull request fixes httpd, mysql, redis, mariadb helm charts for using Shared Cluster.
The commits describes all.

Let's tests shared cluster on Helm Charts first

---

charts/centos/nginx-imagestreams/src/Chart.yaml
charts/redhat/nginx-template/src/templates/buildconfig.yaml
charts/redhat/nginx-template/src/templates/deployment.yaml
charts/redhat/nginx-template/src/templates/tests/test-nginx-connection.yaml
charts/redhat/nginx-template/src/values.schema.json
charts/redhat/nginx-template/src/values.yaml
tests/test_nginx_template.py

Adds also testing all versions for NginX containers. Not only single one.
Values.yaml and values.schema.json was updated
accordingly

Allows to test NginX Helm Chart on shared cluster.

---

.github/workflows/openshift-tests-nos2i.yaml
.github/workflows/openshift-tests-s2i.yaml

Separate S2I and NOS2i tests

---

.github/workflows/openshift-tests-nos2i.yaml
.github/workflows/openshift-tests-s2i.yaml

Fix missing brakes in GitHub Action

---

tests/test_python_django_app.py
tests/test_python_django_psql_persistent.py

Fix Helm charts tests for Python

---

tests/test_httpd_imagestreams.py
tests/test_mariadb_imagestreams.py
tests/test_mysql_imagestreams.py
tests/test_nginx_imagestreams.py
tests/test_nodejs_imagestreams.py
tests/test_perl_imagestreams.py
tests/test_php_cakephp_application.py
tests/test_php_imagestreams.py
tests/test_postgresql_imagestreams.py
tests/test_python_imagestreams.py
tests/test_redis_imagestreams.py
tests/test_ruby_imagestreams.py
tests/test_valkey_imagestreams.py

Do not create project on Shared Cluster every time. One time is enough
The fixture over all classes does this job.

Do not create project on Shared Cluster every time. One time is enough

---

tests/test_httpd_template.py
tests/test_mariadb_template.py
tests/test_mysql_template.py
tests/test_nginx_template.py
tests/test_nodejs_application.py
tests/test_perl_dancer_mysql_template.py
tests/test_php_cakephp_application.py
tests/test_postgresql_template.py
tests/test_redis_template.py
tests/test_ruby_rails_application.py

New charts have prefix `redhat-`

Fix issue caught by renaming

---

charts/redhat/redhat-ruby-imagestreams/src/templates/ruby-imagestream.yaml
charts/redhat/redhat-ruby-rails-application/src/values.yaml
tests/test_httpd_template.py
tests/test_nginx_template.py
tests/test_nodejs_application.py
tests/test_perl_dancer_app.py
tests/test_perl_dancer_mysql_template.py
tests/test_php_cakephp_application.py
tests/test_python_django_app.py
tests/test_python_django_psql_persistent.py
tests/test_ruby_imagestreams.py
tests/test_ruby_rails_application.py

Ruby-31 reached EOL in March 2025.
Let's deprecated

Ruby-31 reached EOL in March 2025.

---

.github/workflows/openshift-tests-nos2i.yaml
.github/workflows/openshift-tests-s2i.yaml

ubuntu-20.04 was retired in March 2025

Switch ubuntu-20.04 -> ubuntu-latest

---

charts/redhat/redhat-valkey-persistent/OWNERS
charts/redhat/redhat-valkey-persistent/src/Chart.yaml
charts/redhat/redhat-valkey-persistent/src/README.md
charts/redhat/redhat-valkey-persistent/src/templates/deployment.yaml
charts/redhat/redhat-valkey-persistent/src/templates/persistentvolumeclaim.yaml
charts/redhat/redhat-valkey-persistent/src/templates/secret.yaml
charts/redhat/redhat-valkey-persistent/src/templates/service.yaml
charts/redhat/redhat-valkey-persistent/src/templates/tests/test-redis-connection.yaml
charts/redhat/redhat-valkey-persistent/src/values.schema.json
charts/redhat/redhat-valkey-persistent/src/values.yaml
tests/test_valkey_template.py

Replace all 'redis' with 'valkey'

Fix valkey helm chart

---

charts/redhat/redhat-nodejs-imagestreams/src/Chart.yaml
charts/redhat/redhat-nodejs-imagestreams/src/templates/nodejs-imagestream.yaml
tests/test_nodejs_application.py
tests/test_nodejs_imagestreams.py

Add NodeJS 22 imagestreams for RHEL8
